In [33]:
import numpy as np

### `Creating Array`

- *np.array()*: Creates a NumPy array

In [34]:
arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


In [35]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- *np.asarray()*: Converts something into an array.

In [37]:
lst = [1,2,3]

arr = np.asarray(lst)
print(arr)

[1 2 3]


- *np.zeros()*: Creates an array filled with zeros.

In [38]:
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [39]:
arr = np.zeros(shape=(2, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


- *np.ones()*: Creates an array filled with ones.

In [40]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [41]:
arr = np.ones(shape=(4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


- *np.empty()*
    - Creates an uninitialized array.
    - The values are not guaranteed to be zero.
    - Use this when performance matters and you're going to fill the array yourself

In [42]:
arr = np.empty(5)
print(arr)

[1. 1. 1. 1. 1.]


In [43]:
arr = np.empty(shape=(3,4))
print(arr)

[[1.25811900e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.92966904e-033 5.27969680e-091 4.31795869e-061]
 [2.83104794e-033 9.96532729e-043 3.99910963e+252 5.92923721e-062]]


- *np.full()*: Creates an array filled with a specific value.

In [44]:
arr = np.full(5, 7)

print(arr)

[7 7 7 7 7]


In [45]:
arr = np.full((2,4), 7)

print(arr)

[[7 7 7 7]
 [7 7 7 7]]


- *np.eye()*: Creates an identity matrix.

In [46]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
arr = np.eye(N = 3, M=5, k=2)
print(arr)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
arr = np.eye(N = 3, M=5, k=-1)
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


- *np.identity()*: creates an identity matrix.

In [49]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
arr = np.identity(n=5, dtype="int")
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### `Creating Sequences`

- *np.arange()*: Like Python's range() but returns a NumPy array.

In [51]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [52]:
arr = np.arange(0, 21, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


- *np.linspace()*: Creates evenly spaced numbers.

In [53]:
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [54]:
arr = np.linspace(0, 10, 3)

print(arr)

[ 0.  5. 10.]


- *np.logspace()*: Creates numbers evenly spaced on a logarithmic scale.

In [55]:
arr = np.logspace(1, 3, 3)

print(arr)

[  10.  100. 1000.]


### `Array Information`

- *.shape*: Returns dimensions.

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape) #! (rows, columns)

(2, 3)


- *.ndim*: Returns number of dimensions.

In [57]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ndim)

2


- *.size*: Number of elements.

In [58]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.size)

6


- *.dtype*: Returns data type.

In [60]:
arr = np.array([1, 2, 3])

print(arr.dtype)

int32


- *.itemsize*: Number of bytes used by each element.

In [59]:
arr = np.array([1, 2, 3], dtype=np.int32)

print(arr.itemsize)

4


- *.nbytes*: Total memory consumed.

In [61]:
arr = np.array([1, 2, 3], dtype=np.int32)

print(arr.nbytes)

12


### `Changing Array Shape`

- *np.reshape()*: Changes the shape without changing the data.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = np.reshape(arr, (2, 3))

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [63]:
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


- *.flatten()*: Converts a multidimensional array into 1D.

In [64]:
arr = np.array([
    [1, 2],
    [3, 4]
])

print(arr.flatten())

[1 2 3 4]


In [65]:
arr = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)

print(arr.flatten())

[1 2 3 4 5 6]


- *.ravel()*: Also converts to 1D.

In [66]:
arr = np.array([
    [1, 2],
    [3, 4]
])

print(arr.ravel())

[1 2 3 4]


In [67]:
arr = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)

print(arr.ravel())

[1 2 3 4 5 6]


- **Main difference:**

    - flatten() generally returns a copy
    - ravel() tries to return a view when possible

- *np.resize()*: Changes size and can repeat values.

In [68]:
arr = np.array([1, 2, 3])

print(np.resize(arr, (2, 4)))

[[1 2 3 1]
 [2 3 1 2]]


In [69]:
arr = np.array([1, 2, 3])

print(np.resize(arr, (2,1)))

[[1]
 [2]]


### `Transposing`

In [70]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [71]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


### `Adding and Removing Dimensions`

In [78]:
arr = np.array([1, 2, 3])

print(arr.shape)

new_arr = np.expand_dims(arr, axis=0)

print(new_arr.shape)
print(new_arr)

print(new_arr.ndim)

(3,)
(1, 3)
[[1 2 3]]
2


In [79]:
arr = np.array([1, 2, 3])

print(arr.shape)

new_arr = np.expand_dims(arr, axis=1)

print(new_arr.shape)
print(new_arr)
print(new_arr.ndim)

(3,)
(3, 1)
[[1]
 [2]
 [3]]
2


In [80]:
arr = np.array([[1, 2, 3]])

print(arr.shape)

new_arr = np.expand_dims(arr, axis=0)

print(new_arr.shape)
print(new_arr)
print(new_arr.ndim)

(1, 3)
(1, 1, 3)
[[[1 2 3]]]
3


In [81]:
arr = np.array([[1, 2, 3]])

print(arr.shape)

new_arr = np.expand_dims(arr, axis=1)

print(new_arr.shape)
print(new_arr)
print(new_arr.ndim)

(1, 3)
(1, 1, 3)
[[[1 2 3]]]
3


- *np.squeeze()*: Removes dimensions of size 1

In [82]:
arr = np.array([[1, 2, 3]])

print(arr.shape)

new_arr = np.squeeze(arr)

print(new_arr.shape)

(1, 3)
(3,)


In [85]:
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ]
])

new_arr = np.squeeze(arr)
print(new_arr)
print(new_arr.ndim)
print(new_arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


### `Joining Arrays`

- *np.concatenate()*: Joins arrays.
    - axis: 0 --> column
    - axis: 1 --> row

In [86]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)

[1 2 3 4 5 6]


In [87]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [88]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(np.concatenate((a, b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]
